services:
  php:
    build: .
    container_name: php-evaluation
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx-evaluation
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mariadb:latest
    container_name: database-evaluation
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: unicorn
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
